// Pulls the published resume (github.com/aranlucas/resume → Cloudflare) into
// src/generated/. Runs before every build; if the fetch fails, the committed
// snapshot is kept so builds never break on a network hiccup.
// Override the source with RESUME_API_URL (e.g. a local `_site` server).
// Run with Node 24+, which strips the types natively.

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const base = (process.env.RESUME_API_URL ?? "https://resume-api.aranlucas.workers.dev").replace(
  /\/$/u,
  "",
);
const outDir = resolve(import.meta.dirname, "../src/generated");

async function get(file: string): Promise<string> {
  const res = await fetch(`${base}/${file}`, { signal: AbortSignal.timeout(10_000) });
  if (!res.ok) throw new Error(`GET ${base}/${file} → ${res.status}`);
  return res.text();
}

try {
  const [json, markdown] = await Promise.all([get("resume.json"), get("resume.md")]);
  // Refuse to write a broken snapshot.
  JSON.parse(json);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, "resume.json"), json);
  // A TS module (not a raw .md) so it bundles without runtime fs reads; the
  // template literal keeps git diffs readable.
  const escaped = markdown.replaceAll(/[\\`$]/gu, String.raw`\$&`);
  writeFileSync(
    resolve(outDir, "resume-markdown.ts"),
    `// Generated by scripts/sync-resume.mts — do not edit.\nexport const RESUME_MARKDOWN = \`${escaped}\`;\n`,
  );
  console.log(`Synced resume from ${base}`);
} catch (error) {
  console.warn(`Resume sync failed, keeping committed snapshot: ${String(error)}`);
}
